"use strict";
(()=>{const OVERLAY_CLASS="short-shifter-overlay",STYLE_ID="short-shifter-styles",TARGET_RATIO=9/16,RATIO_TOLERANCE=.05;let shortsVisible=false,scanTimer=null;
function injectStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`.${OVERLAY_CLASS}{position:absolute!important;z-index:2147483647!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:hidden!important;background:radial-gradient(circle at 50% 45%,#181818 0%,#090909 70%)!important;border-radius:inherit!important;pointer-events:none!important;box-sizing:border-box!important}.${OVERLAY_CLASS} .short-shifter-poo{display:block!important;font-family:"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif!important;font-size:clamp(28px,22%,76px)!important;line-height:1!important;user-select:none!important;animation:short-shifter-bounce 850ms cubic-bezier(.25,.8,.25,1) infinite!important;transform-origin:center bottom!important}.${OVERLAY_CLASS} .short-shifter-face{position:absolute!important;width:.8em!important;height:.8em!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:.5em!important;transform:translate(.15em,-.15em) scaleX(0)!important;animation:short-shifter-wink 3s ease-in-out infinite!important}@keyframes short-shifter-bounce{0%,100%{transform:translateY(5px) rotate(-3deg)}50%{transform:translateY(-8px) rotate(3deg)}}@keyframes short-shifter-wink{0%,72%,100%{transform:translate(.15em,-.15em) scaleX(0)}75%,82%{transform:translate(.15em,-.15em) scaleX(1)}}`;document.documentElement.appendChild(s)}
function isNearNineBySixteen(w,h){return !!w&&!!h&&Math.abs(w/h-TARGET_RATIO)/TARGET_RATIO<=RATIO_TOLERANCE}
function getRect(e){const r=e.getBoundingClientRect();if(r.width<30||r.height<50||r.bottom< -100||r.top>innerHeight+500)return null;return r}
function candidates(){return document.querySelectorAll('img,video,canvas,ytd-thumbnail,yt-thumbnail-view-model,ytd-rich-item-renderer,ytd-grid-video-renderer,ytd-video-renderer,a#thumbnail')}
function getOverlay(h){return h.querySelector(`:scope > .${OVERLAY_CLASS}`)}function findHost(e){let p=e;for(let i=0;i<5&&p;i++){const pos=getComputedStyle(p).position;if(["relative","absolute","fixed"].includes(pos))return p;p=p.parentElement}return e.parentElement||e}
function createOverlay(target,r){const h=findHost(target);if(!h)return;if(getComputedStyle(h).position==="static")h.style.position="relative";const hr=h.getBoundingClientRect(),o=document.createElement("div");o.className=OVERLAY_CLASS;o.setAttribute("aria-label","YouTube Short hidden");Object.assign(o.style,{left:`${r.left-hr.left}px`,top:`${r.top-hr.top}px`,width:`${r.width}px`,height:`${r.height}px`});const poo=document.createElement("span");poo.className="short-shifter-poo";poo.textContent="💩";const face=document.createElement("span");face.className="short-shifter-face";face.textContent="😉";o.append(poo,face);h.appendChild(o)}
function process(e){if(!(e instanceof HTMLElement)||e.classList.contains(OVERLAY_CLASS)||e.closest(`.${OVERLAY_CLASS}`))return;const h=findHost(e);if(!h)return;if(shortsVisible){getOverlay(h)?.remove();return}const r=getRect(e);if(!r||!isNearNineBySixteen(r.width,r.height)||getOverlay(h))return;createOverlay(e,r)}
function scan(){scanTimer=null;injectStyles();for(const e of candidates())process(e)}function schedule(){if(scanTimer===null)scanTimer=setTimeout(scan,150)}function removeAll(){document.querySelectorAll(`.${OVERLAY_CLASS}`).forEach(e=>e.remove())}
function start(){new MutationObserver(ms=>{if(ms.some(m=>m.addedNodes.length||m.removedNodes.length))schedule()}).observe(document.documentElement,{childList:true,subtree:true});addEventListener("resize",schedule,{passive:true});addEventListener("scroll",schedule,{passive:true});document.addEventListener("yt-navigate-finish",schedule)}
async function init(){injectStyles();shortsVisible=Boolean((await chrome.storage.local.get({shortsVisible:false})).shortsVisible);start();scan();[500,1500,3000].forEach(t=>setTimeout(scan,t))}
chrome.runtime.onMessage.addListener(m=>{if(m?.type!=="SHORTS_VISIBILITY_CHANGED")return;shortsVisible=Boolean(m.shortsVisible);shortsVisible?removeAll():scan()});init()})();
